# Generated by Django 4.0.3 on 2024-02-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.department'),
        ),
    ]
